In [56]:
import pandas as kg

In [57]:
bunny=kg.read_csv(r"C:\Users\STUDENT\Desktop\SonalkgML\DataSets-master\bmi_male_female.csv")

In [58]:
bunny

     Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
5      Male     189     104      3
6      Male     147      92      5
7      Male     154     111      5
8      Male     174      90      3
9    Female     169     103      4
10     Male     195      81      2
11   Female     159      80      4
12   Female     192     101      3
13     Male     155      51      2
14     Male     191      79      2
15   Female     153     107      5
16   Female     157     110      5
17     Male     140     129      5
18     Male     144     145      5
19     Male     172     139      5
20     Male     157     110      5
21   Female     153     149      5
22   Female     169      97      4
23     Male     185     139      5
24   Female     172      67      2
25   Female     151      64      3
26     Male     190      95      3
27     Male     187      62      1
28   Female     163     159      5
29     Male     179     152      5
..      ...     ...     ...    ...
470    Male     147     142      5
471    Male     154     112      5
472  Female     178      65      2
473    Male     195     153      5
474  Female     167      79      3
475    Male     183     131      4
476  Female     164     142      5
477    Male     167      64      2
478  Female     151      55      2
479  Female     147     107      5
480  Female     155     115      5
481  Female     172     108      4
482  Female     142      86      5
483    Male     146      85      4
484  Female     188     115      4
485    Male     173     111      4
486  Female     160     109      5
487    Male     187      80      2
488    Male     198     136      4
489  Female     179     150      5
490  Female     164      59      2
491  Female     146     147      5
492  Female     198      50      0
493  Female     170      53      1
494    Male     152      98      5
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [59]:
bunny.shape

(500, 4)

In [60]:
num_male=bunny[bunny["Gender"]=='Male']

In [61]:
num_male

    Gender  Height  Weight  Index
0     Male     174      96      4
1     Male     189      87      2
4     Male     149      61      3
5     Male     189     104      3
6     Male     147      92      5
7     Male     154     111      5
8     Male     174      90      3
10    Male     195      81      2
13    Male     155      51      2
14    Male     191      79      2
17    Male     140     129      5
18    Male     144     145      5
19    Male     172     139      5
20    Male     157     110      5
23    Male     185     139      5
26    Male     190      95      3
27    Male     187      62      1
29    Male     179     152      5
30    Male     153     121      5
31    Male     178      52      1
37    Male     144      80      4
42    Male     157      56      2
43    Male     161     118      5
45    Male     185      76      2
47    Male     181     111      4
48    Male     161      72      3
49    Male     140     152      5
52    Male     163     110      5
53    Male     172     105      4
54    Male     196     116      4
..     ...     ...     ...    ...
438   Male     188      65      1
441   Male     182      73      2
442   Male     143     149      5
443   Male     152     146      5
445   Male     159     140      5
446   Male     146      70      4
449   Male     159     145      5
450   Male     162     157      5
453   Male     182      50      0
455   Male     176      77      2
458   Male     154      81      4
460   Male     179     123      4
461   Male     152     132      5
462   Male     179      56      1
465   Male     158     127      5
467   Male     145     142      5
468   Male     161     115      5
469   Male     198     109      3
470   Male     147     142      5
471   Male     154     112      5
473   Male     195     153      5
475   Male     183     131      4
477   Male     167      64      2
483   Male     146      85      4
485   Male     173     111      4
487   Male     187      80      2
488   Male     198     136      4
494   Male     152      98      5
498   Male     150      95      5
499   Male     173     131      5

[245 rows x 4 columns]

In [62]:
len(num_male)

245

In [63]:
overw=num_male[num_male["Index"]==3]

In [64]:
len(overw)

32

In [65]:
num_female=bunny[bunny["Gender"]=='Female']

In [66]:
overwf=num_female[num_female["Index"]==3]

In [67]:
len(overwf)

36

In [68]:
index_name=kg.Series(["Extermely weak","weak","Normal","Overweight","Obesity","Extreme Obesity"])

In [69]:
index_name

0     Extermely weak
1               weak
2             Normal
3         Overweight
4            Obesity
5    Extreme Obesity
dtype: object

In [70]:
index_name[4]

'Obesity'

In [71]:
#encode male.............0,Female....1
bunny.Gender[bunny.Gender=="Male"]=0
bunny.Gender[bunny.Gender=="Female"]=1

C:\Users\STUDENT\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\STUDENT\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [72]:
bunny

    Gender  Height  Weight  Index
0        0     174      96      4
1        0     189      87      2
2        1     185     110      4
3        1     195     104      3
4        0     149      61      3
5        0     189     104      3
6        0     147      92      5
7        0     154     111      5
8        0     174      90      3
9        1     169     103      4
10       0     195      81      2
11       1     159      80      4
12       1     192     101      3
13       0     155      51      2
14       0     191      79      2
15       1     153     107      5
16       1     157     110      5
17       0     140     129      5
18       0     144     145      5
19       0     172     139      5
20       0     157     110      5
21       1     153     149      5
22       1     169      97      4
23       0     185     139      5
24       1     172      67      2
25       1     151      64      3
26       0     190      95      3
27       0     187      62      1
28       1     163     159      5
29       0     179     152      5
..     ...     ...     ...    ...
470      0     147     142      5
471      0     154     112      5
472      1     178      65      2
473      0     195     153      5
474      1     167      79      3
475      0     183     131      4
476      1     164     142      5
477      0     167      64      2
478      1     151      55      2
479      1     147     107      5
480      1     155     115      5
481      1     172     108      4
482      1     142      86      5
483      0     146      85      4
484      1     188     115      4
485      0     173     111      4
486      1     160     109      5
487      0     187      80      2
488      0     198     136      4
489      1     179     150      5
490      1     164      59      2
491      1     146     147      5
492      1     198      50      0
493      1     170      53      1
494      0     152      98      5
495      1     150     153      5
496      1     184     121      4
497      1     141     136      5
498      0     150      95      5
499      0     173     131      5

[500 rows x 4 columns]

In [73]:
b_input=bunny.iloc[:,0:3]

In [74]:
b_input

    Gender  Height  Weight
0        0     174      96
1        0     189      87
2        1     185     110
3        1     195     104
4        0     149      61
5        0     189     104
6        0     147      92
7        0     154     111
8        0     174      90
9        1     169     103
10       0     195      81
11       1     159      80
12       1     192     101
13       0     155      51
14       0     191      79
15       1     153     107
16       1     157     110
17       0     140     129
18       0     144     145
19       0     172     139
20       0     157     110
21       1     153     149
22       1     169      97
23       0     185     139
24       1     172      67
25       1     151      64
26       0     190      95
27       0     187      62
28       1     163     159
29       0     179     152
..     ...     ...     ...
470      0     147     142
471      0     154     112
472      1     178      65
473      0     195     153
474      1     167      79
475      0     183     131
476      1     164     142
477      0     167      64
478      1     151      55
479      1     147     107
480      1     155     115
481      1     172     108
482      1     142      86
483      0     146      85
484      1     188     115
485      0     173     111
486      1     160     109
487      0     187      80
488      0     198     136
489      1     179     150
490      1     164      59
491      1     146     147
492      1     198      50
493      1     170      53
494      0     152      98
495      1     150     153
496      1     184     121
497      1     141     136
498      0     150      95
499      0     173     131

[500 rows x 3 columns]

In [75]:
#input mydata[["gender","height","weight"]]
b_target=bunny["Index"]

In [76]:
b_target

0      4
1      2
2      4
3      3
4      3
5      3
6      5
7      5
8      3
9      4
10     2
11     4
12     3
13     2
14     2
15     5
16     5
17     5
18     5
19     5
20     5
21     5
22     4
23     5
24     2
25     3
26     3
27     1
28     5
29     5
      ..
470    5
471    5
472    2
473    5
474    3
475    4
476    5
477    2
478    2
479    5
480    5
481    4
482    5
483    4
484    4
485    4
486    5
487    2
488    4
489    5
490    2
491    5
492    0
493    1
494    5
495    5
496    4
497    5
498    5
499    5
Name: Index, dtype: int64

In [77]:
b_input.shape

(500, 3)

In [78]:
import numpy as np

In [79]:
b=b_input.values.reshape(500,3)

In [80]:
b

array([[0, 174, 96],
       [0, 189, 87],
       [1, 185, 110],
       ...,
       [1, 141, 136],
       [0, 150, 95],
       [0, 173, 131]], dtype=object)

In [81]:
s=b_target.values.reshape(-1,1)

In [82]:
s

array([[4],
       [2],
       [4],
       [3],
       [3],
       [3],
       [5],
       [5],
       [3],
       [4],
       [2],
       [4],
       [3],
       [2],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [3],
       [3],
       [1],
       [5],
       [5],
       [5],
       [1],
       [1],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [4],
       [2],
       [4],
       [4],
       [3],
       [5],
       [5],
       [1],
       [5],
       [4],
       [4],
       [3],
       [4],
       [5],
       [3],
       [5],
       [0],
       [5],
       [0],
       [2],
       [5],
       [5],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [5],
       [2],
       [3],
       [4],
       [4],
       [4],
       [4],
       [0],
       [3],
       [5],
       [3],
       [4],
       [5],
       [0],
       [5],
       [5],
       [5],
       [5],
       [5],
       [3],
       [3],
       [2],
       [4],
       [5],
       [4],
       [5],
       [1],
       [0],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [4],
       [3],
       [2],
       [5],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [5],
       [2],
       [5],
       [2],
       [5],
       [4],
       [5],
       [5],
       [5],
       [3],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [5],
       [4],
       [3],
       [5],
       [3],
       [3],
       [0],
       [3],
       [3],
       [5],
       [5],
       [4],
       [3],
       [5],
       [3],
       [4],
       [2],
       [2],
       [3],
       [5],
       [4],
       [2],
       [4],
       [5],
       [3],
       [2],
       [4],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [3],
       [5],
       [3],
       [3],
       [4],
       [4],
       [2],
       [3],
       [3],
       [5],
       [3],
       [5],
       [4],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [4],
       [4],
       [5],
       [5],
       [1],
       [3],
       [4],
       [4],
       [5],
       [4],
       [5],
       [4],
       [3],
       [4],
       [4],
       [5],
       [5],
       [5],
       [0],
       [5],
       [5],
       [5],
       [5],
       [5],
       [2],
       [5],
       [4],
       [5],
       [0],
       [5],
       [3],
       [4],
       [5],
       [5],
       [4],
       [2],
       [3],
       [3],
       [4],
       [3],
       [5],
       [5],
       [2],
       [5],
       [3],
       [2],
       [1],
       [5],
       [0],
       [5],
       [3],
       [5],
       [3],
       [4],
       [3],
       [5],
       [5],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5],
       [2],
       [4],
       [5],
       [5],
       [5],
       [5],
       [1],
       [5],
       [5],
       [4],
       [0],
       [3],
       [3],
       [4],
       [2],
       [3],
       [1],
       [1],
       [5],
       [5],
       [4],
       [4],
       [4],
       [4],
       [5],
       [2],
       [5],
       [4],
       [3],
       [3],
       [4],
       [5],
       [5],
       [2],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [4],
       [5],
       [4],
       [5],
       [5],
       [1],
       [5],
       [5],
       [5],
       [5],
       [2],
       [2],
       [5],
       [3],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [5],
       [4],
       [2],
       [2],
       [4],
       [3],
       [3],
       [5],
       [4],
       [2],
       [2],
       [2],
       [2],
       [5],
       [5],
       [4],
       [5],
       [3],
       [4],
       [4],
       [3],
       [4],
       [4],
       [2],
       [2],
       [5],
       [2],
       [2],
       [2],
       [2],
       [5],
       [0],
       [3],
       [4],
       [5],
       [1],
       [4],
       [1],
       [4],
       [5],
       [4],
       [5],
       [5],
       [3],
       [4],
       [5],
       [4],
       [3],
       [5],
       [1],
       [2],
       [4],
       [5],
       [5],
       [5],
       [5],
       [3],
       [5],
       [1],
       [4],
       [5],
       [5],
       [2],
       [5],
       [4],
       [3],
       [2],
       [2],
       [2],
       [2],
       [3],
       [5],
       [3],
       [3],
       [5],
       [3],
       [5],
       [3],
       [4],
       [2],
       [4],
       [4],
       [5],
       [2],
       [5],
       [5],
       [5],
       [1],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [5],
       [2],
       [1],
       [5],
       [5],
       [4],
       [1],
       [1],
       [4],
       [4],
       [4],
       [4],
       [2],
       [5],
       [5],
       [4],
       [2],
       [5],
       [5],
       [5],
       [1],
       [5],
       [4],
       [2],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [5],
       [5],
       [5],
       [4],
       [5],
       [0],
       [2],
       [2],
       [4],
       [2],
       [4],
       [5],
       [4],
       [5],
       [1],
       [5],
       [2],
       [5],
       [3],
       [5],
       [5],
       [3],
       [5],
       [5],
       [2],
       [5],
       [3],
       [4],
       [5],
       [2],
       [2],
       [5],
       [5],
       [4],
       [5],
       [4],
       [4],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [0],
       [1],
       [5],
       [5],
       [4],
       [5],
       [5],
       [5]], dtype=int64)

In [83]:
from sklearn.neighbors import KNeighborsClassifier

In [84]:
X_train=b[:350]
X_test=b[350:]
Y_train=s[:350]
Y_test=s[350:]

In [85]:
teacher=KNeighborsClassifier()

In [86]:
learner=teacher.fit(X_train,Y_train)

C:\Users\STUDENT\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  if __name__ == '__main__':

In [87]:
p=learner.predict([[1,170,53]])

In [88]:
index_name[p]

2    Normal
dtype: object

In [89]:
p=learner.predict([[1,160,54]])

In [90]:
index_name[p]

2    Normal
dtype: object

In [91]:
p=learner.predict([[0,170,67]])

In [92]:
index_name[p]

2    Normal
dtype: object

In [93]:
Ya=Y_test
Yp=learner.predict(X_test)

In [94]:
Yalist=list(Ya)
Yplist=list(Yp)

In [95]:
table=kg.DataFrame({"Ya":Yalist,"Yp":Yplist})

In [96]:
table

      Ya  Yp
0    [2]   3
1    [2]   2
2    [2]   2
3    [5]   5
4    [0]   0
5    [3]   3
6    [4]   4
7    [5]   5
8    [1]   1
9    [4]   5
10   [1]   1
11   [4]   5
12   [5]   5
13   [4]   4
14   [5]   5
15   [5]   4
16   [3]   3
17   [4]   4
18   [5]   5
19   [4]   4
20   [3]   3
21   [5]   5
22   [1]   1
23   [2]   2
24   [4]   4
25   [5]   5
26   [5]   5
27   [5]   5
28   [5]   4
29   [3]   3
..   ...  ..
120  [5]   5
121  [5]   5
122  [2]   2
123  [5]   4
124  [3]   3
125  [4]   4
126  [5]   5
127  [2]   2
128  [2]   2
129  [5]   5
130  [5]   5
131  [4]   4
132  [5]   5
133  [4]   5
134  [4]   4
135  [4]   4
136  [5]   5
137  [2]   2
138  [4]   4
139  [5]   5
140  [2]   2
141  [5]   5
142  [0]   0
143  [1]   2
144  [5]   5
145  [5]   5
146  [4]   4
147  [5]   5
148  [5]   5
149  [5]   5

[150 rows x 2 columns]

In [97]:
from sklearn.metrics import accuracy_score

In [98]:
acc=accuracy_score(Ya,Yp)*100

In [1]:
acc

NameError: name 'acc' is not defined

In [2]:
import cv2

ImportError: DLL load failed: The specified module could not be found.